### ISSUE TITLE
Add Google Authentication for sign up and sign in

### ISSUE THREAD

**Issue by noumandev11** [CoalAI/boilerplate-react#5]

**Comment by aishatasaduq** [comment]
doing r&d on which package to use.
right now implementing react-oauth/google

**Comment by aishatasaduq** [comment]
update:
I have used react-oauth/google for google authentication. It gives access_token which i send at backend to get access and refresh tokens.
For this i need to update django backend as package we are using right now is not for drf. Kindly approve this so that i can ask noman bhai to create task for django boiler plate.
@MKRNaqeebi

**Comment by aishatasaduq** [comment]
As i changed backend so frontend needed to be changed accordingly. It took me almost 3 hours as i was having issue with redirect

**Comment by noumandev11** [comment]
completed
